#!/bin/bash
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/ColorLogger.py > ColorLogger.py
if [[ $? = 0 ]]
then
  echo "Updated ColorLogger.py"
else
  echo "Updation of 'ColorLogger.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/config.py > config.py
if [[ $? = 0 ]]
then
  echo "Updated config.py"
else
  echo "Updation of 'config.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/conversation.py > conversation.py
if [[ $? = 0 ]]
then
  echo "Updated conversation.py"
else
  echo "Updation of 'conversation.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/engine_wrapper.py > engine_wrapper.py
if [[ $? = 0 ]]
then
  echo "Updated engine_wrapper.py"
else
  echo "Updation of 'engine_wrapper.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/lichess-bot.py > lichess-bot.py
if [[ $? = 0 ]]
then
  echo "Updated lichess-bot.py"
else
  echo "Updation of 'lichess-bot.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/lichess.py > lichess.py
if [[ $? = 0 ]]
then
  echo "Updated lichess.py"
else
  echo "Updation of 'lichess.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/logging_pool.py > logging_pool.py
if [[ $? = 0 ]]
then
  echo "Updated logging_pool.py"
else
  echo "Updation of 'logging_pool.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/model.py > model.py
if [[ $? = 0 ]]
then
  echo "Updated model.py"
else
  echo "Updation of 'model.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/requirements.txt > requirements.txt
if [[ $? = 0 ]]
then
  echo "Updated requirements.txt"
else
  echo "Updation of 'requirements.txt' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/test_bot/__init__.py > test_bot/__init__.py
if [[ $? = 0 ]]
then
  echo "Updated test_bot/__init__.py"
else
  echo "Updation of 'test_bot/__init__.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/test_bot/conftest.py > test_bot/conftest.py
if [[ $? = 0 ]]
then
  echo "Updated test_bot/conftest.py"
else
  echo "Updation of 'test_bot/conftest.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/test_bot/lichess.py > test_bot/lichess.py
if [[ $? = 0 ]]
then
  echo "Updated test_bot/lichess.py"
else
  echo "Updation of 'test_bot/lichess.py' failed exitcode:"$?
fi
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/test_bot/test_bot.py > test_bot/test_bot.py
if [[ $? = 0 ]]
then
  echo "Updated test_bot/test_bot.py"
else
  echo "Updation of 'test_bot/test_bot.py' failed exitcode:"$?
fi
echo "Please update 'config.yml' & this script manually."