#!/bin/bash

Updated () {
  echo "Updated $1"
}
Failed () {
  echo "Updation of '$1' failed exitcode:$?"
}

Update () {
curl -sf https://raw.githubusercontent.com/ShailChoksi/lichess-bot/master/$1 > $1
if [[ $? = 0 ]]
then
  Updated $1
else
  Failed $1
fi
}

Update ColorLogger.py
Update config.py
Update conversation.py
Update engine_wrapper.py
Update lichess-bot.py
Update lichess.py
Update logging_pool.py
Update model.py
Update requirements.txt
Update strategies.py
Update test_bot/__init__.py
Update test_bot/conftest.py
Update test_bot/lichess.py
Update test_bot/test_bot.py
sed -i "s/config.yml.default/config.yml/" test_bot/test_bot.py 
echo "Please update 'config.yml' & this script manually."