# This workflow will install Python dependencies and run mypy

name: Mypy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mypy:
    if: "github.event_name == 'pull_request' || contains(github.event.head_commit.message, 'Auto update version')"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: [3.8, "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-requests types-PyYAML
        pip install -r requirements.txt
    - name: Run mypy
      run: |
        mypy --strict .
